export const ABOUT_ME_EN = {
  desktop: [
    "Hey, I’m 'Lucas', 27 years old, living in 'Tubarão, SC, Brazil', and I’m a front end developer.",
    " ",
    "My journey into programming took an unexpected turn back in 2016 when I dropped out of psychology graduation,",
    "and started a technical course in programming, mainly to keep myself busy.",
    "since then, I‘ve developed this new addiction to coding.",
    " ",
    "Then I got my first job as a developer in 2017, and I’ve been working with it ever since.",
  ],
  mobile: [
    "Hey, I’m 'Lucas', 27 years old,",
    "living in 'Tubarão, SC, Brazil',",
    "and I’m a front end developer.",
    " ",
    "My journey into programming took",
    "an unexpected turn back in 2016",
    "when I dropped out of psychology,",
    "and started a technical course in",
    "programming, mainly to keep myself", 
    "busy.",
    " ",
    "Since then, I‘ve developed", 
    "this new addiction to coding.",
    " ",
    "Then I got my first job",
    "as a developer in 2017,",
    "and I’ve been working with",
    "it ever since.",
  ],
};

export const ABOUT_ME_PT = {
  desktop: [
    "Olá, eu sou 'Lucas', tenho 27 anos, moro em 'Tubarão, SC, Brasil', e sou desenvolvedor front-end.",
    " ",
    "Minha jornada na programação começou de um jeito inesperado em 2016 quando larguei a faculdade de psicologia",
    "e iniciei um curso técnico em programação, inicialmente apenas para me manter ocupado.",
    "desde então, criei essa vício por programação.",
    " ",
    "Então consegui meu primeiro emprego como desenvolvedor em 2017, e venho trabalhando com isso desde então.",
  ],
  mobile: [
    "Olá, eu sou 'Lucas', tenho 27 anos,",
    "moro em 'Tubarão, SC, Brasil',",
    "e sou desenvolvedor front-end.",
    " ",
    "Minha jornada na programação começou",
    "de um jeito inesperado em 2016",
    "quando larguei a psicologia,",
    "e iniciei um curso técnico em",
    "programação, inicialmente apenas",
    "para me manter ocupado.",
    " ",
    "Desde então, criei essa vício",
    "por programação.",
    " ",
    "Então consegui meu primeiro emprego",
    "como desenvolvedor em 2017,",
    "e venho trabalhando com isso",
    "desde então.",
  ]
};
